export default [
    {
        id:1,
        model:'AT59845895',
        image:require('../../assets/images/jcb1.png')
    },
    {
        id:2,
        model:'BD8459876',
        image:require('../../assets/images/jcb2.png')
    },
    {
        id:3,
        model:'DX8739515',
        image:require('../../assets/images/jcb3.png')
    },
    {
        id:4,
        model:'BD8459876',
        image:require('../../assets/images/jcb2.png')
    },
    {
        id:5,
        model:'DX8739515',
        image:require('../../assets/images/jcb3.png')
    }
];