export default [
    {
        id: 1,
        image: require('../../assets/images/bulldozer_Image1.png'),
        checkImage: require('../../assets/images/check_icon.png'),
        notCheckImage: require('../../assets/images/x_icon.png'),
        model: '424B2 BACKHOE LOADER',
        connected:'Connected',
        serial: 'Serial: K7C01126',
        smuHours: 'SMU Hours: 280',
        amcValidity: 'Dec 21',
        requestButtonText: 'Request Service',
        orderButtonText: 'Order Parts',
        planButtonText: 'My Plan',
    },
    {
        id: 2,
        image: require('../../assets/images/bulldozer_Image2.png'),
        checkImage: require('../../assets/images/check_icon.png'),
        notCheckImage: require('../../assets/images/x_icon.png'),
        model: '320D3 Excavator',
        connected:'Connected',
        serial: 'Serial: AT5984589566',
        smuHours: 'SMU Hours: 150',
        amcValidity: 'Dec 21',
        requestButtonText: 'Request Service',
        orderButtonText: 'Order Parts',
        planButtonText: 'My Plan',
    },
    {
        id: 3,
        image: require('../../assets/images/bulldozer_Image3.png'),
        checkImage: require('../../assets/images/check_icon.png'),
        notCheckImage: require('../../assets/images/x_icon.png'),
        model: 'D6R2 TRACK-Type TRACTOR',
        connected:'Not Connected',
        notConnected:'Not Connected',
        serial: 'Serial: AT5984589566',
        smuHours: 'SMU Hours: 210',
        amcValidity: 'Dec 21',
        requestButtonText: 'Request Service',
        orderButtonText: 'Order Parts',
        planButtonText: 'My Plan',
    }
]